// Code generated by microgen 1.0.4. DO NOT EDIT.

package service

import (
	"context"
	log "github.com/go-kit/kit/log"
	service "github.com/justyntemme/wp/club"
	"time"
)

// LoggingMiddleware writes params, results and working time of method call to provided logger after its execution.
func LoggingMiddleware(logger log.Logger) Middleware {
	return func(next service.ClubService) service.ClubService {
		return &loggingMiddleware{
			logger: logger,
			next:   next,
		}
	}
}

type loggingMiddleware struct {
	logger log.Logger
	next   service.ClubService
}

func (M loggingMiddleware) GetClubById(arg0 context.Context, arg1 string) (res0 string, res1 error) {
	defer func(begin time.Time) {
		M.logger.Log(
			"method", "GetClubById",
			"message", "GetClubById called",
			"request", logGetClubByIdRequest{Id: arg1},
			"response", logGetClubByIdResponse{Result: res0},
			"err", res1,
			"took", time.Since(begin))
	}(time.Now())
	return M.next.GetClubById(arg0, arg1)
}

type (
	logGetClubByIdRequest struct {
		Id string
	}
	logGetClubByIdResponse struct {
		Result string
	}
)
