// Code generated by microgen 1.0.4. DO NOT EDIT.

package service

import service "github.com/justyntemme/wp/club"

// Service middleware (closure).
type Middleware func(service.ClubService) service.ClubService
