// Code generated by microgen 1.0.4. DO NOT EDIT.

package transportgrpc

import (
	grpckit "github.com/go-kit/kit/transport/grpc"
	pb "github.com/justyntemme/wp/vote/proto"
	transport "github.com/justyntemme/wp/vote/transport"
	grpc "google.golang.org/grpc"
)

func NewGRPCClient(conn *grpc.ClientConn, addr string, opts ...grpckit.ClientOption) transport.EndpointsSet {
	return transport.EndpointsSet{
		GetVoteByIdEndpoint: grpckit.NewClient(
			conn, addr, "GetVoteById",
			_Encode_GetVoteById_Request,
			_Decode_GetVoteById_Response,
			pb.GetVoteByIdResponse{},
			opts...,
		).Endpoint(),
		GetVotesByClubIdEndpoint: grpckit.NewClient(
			conn, addr, "GetVotesByClubId",
			_Encode_GetVotesByClubId_Request,
			_Decode_GetVotesByClubId_Response,
			pb.GetVotesByClubIdResponse{},
			opts...,
		).Endpoint(),
		GetVotesByUserIdEndpoint: grpckit.NewClient(
			conn, addr, "GetVotesByUserId",
			_Encode_GetVotesByUserId_Request,
			_Decode_GetVotesByUserId_Response,
			pb.GetVotesByUserIdResponse{},
			opts...,
		).Endpoint(),
	}
}
