// Code generated by microgen 1.0.4. DO NOT EDIT.

package transporthttp

import (
	httpkit "github.com/go-kit/kit/transport/http"
	transport "github.com/justyntemme/wp/user/transport"
	"net/url"
)

func NewHTTPClient(u *url.URL, opts ...httpkit.ClientOption) transport.EndpointsSet {
	return transport.EndpointsSet{GetUserByIdEndpoint: httpkit.NewClient(
		"POST", u,
		_Encode_GetUserById_Request,
		_Decode_GetUserById_Response,
		opts...,
	).Endpoint()}
}
