// Code generated by microgen 1.0.4. DO NOT EDIT.

package transporthttp

import (
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	transport "github.com/justyntemme/wp/user/transport"
	http1 "net/http"
)

func NewHTTPHandler(endpoints *transport.EndpointsSet, opts ...http.ServerOption) http1.Handler {
	mux := mux.NewRouter()
	mux.Methods("POST").Path("/get-user-byid").Handler(
		http.NewServer(
			endpoints.GetUserByIdEndpoint,
			_Decode_GetUserById_Request,
			_Encode_GetUserById_Response,
			opts...))
	return mux
}
