// Code generated by microgen 1.0.4. DO NOT EDIT.

package transportgrpc

import (
	grpckit "github.com/go-kit/kit/transport/grpc"
	pb "github.com/justyntemme/wp/user/proto"
	transport "github.com/justyntemme/wp/user/transport"
	grpc "google.golang.org/grpc"
)

func NewGRPCClient(conn *grpc.ClientConn, addr string, opts ...grpckit.ClientOption) transport.EndpointsSet {
	return transport.EndpointsSet{GetUserByIdEndpoint: grpckit.NewClient(
		conn, addr, "GetUserById",
		_Encode_GetUserById_Request,
		_Decode_GetUserById_Response,
		pb.GetUserByIdResponse{},
		opts...,
	).Endpoint()}
}
