// Code generated by microgen 1.0.4. DO NOT EDIT.

// DO NOT EDIT.
package transportgrpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	pb "github.com/justyntemme/wp/user/proto"
	transport "github.com/justyntemme/wp/user/transport"
	context "golang.org/x/net/context"
)

type userServiceServer struct {
	pb.UnimplementedUserServiceServer
	getUserById grpc.Handler
}

func NewGRPCServer(endpoints *transport.EndpointsSet, opts ...grpc.ServerOption) pb.UserServiceServer {
	return &userServiceServer{getUserById: grpc.NewServer(
		endpoints.GetUserByIdEndpoint,
		_Decode_GetUserById_Request,
		_Encode_GetUserById_Response,
		opts...,
	)}
}

func newOneToManyStreamServer(endpoint transport.OneToManyStreamEndpoint) transport.OneToManyStreamEndpoint {
	return endpoint
}

func newManyToOneStreamServer(endpoint transport.ManyToOneStreamEndpoint) transport.ManyToOneStreamEndpoint {
	return endpoint
}

func newManyToManyStreamServer(endpoint transport.ManyToManyStreamEndpoint) transport.ManyToManyStreamEndpoint {
	return endpoint
}

func (S *userServiceServer) GetUserById(ctx context.Context, req *pb.GetUserByIdRequest) (*pb.GetUserByIdResponse, error) {
	_, resp, err := S.getUserById.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return resp.(*pb.GetUserByIdResponse), nil
}
