// Code generated by microgen 1.0.4. DO NOT EDIT.

package transporthttp

import (
	httpkit "github.com/go-kit/kit/transport/http"
	transport "github.com/justyntemme/wp/club/transport"
	"net/url"
)

func NewHTTPClient(u *url.URL, opts ...httpkit.ClientOption) transport.EndpointsSet {
	return transport.EndpointsSet{
		GetAllClubsNearMeEndpoint: httpkit.NewClient(
			"POST", u,
			_Encode_GetAllClubsNearMe_Request,
			_Decode_GetAllClubsNearMe_Response,
			opts...,
		).Endpoint(),
		GetClubByIdEndpoint: httpkit.NewClient(
			"POST", u,
			_Encode_GetClubById_Request,
			_Decode_GetClubById_Response,
			opts...,
		).Endpoint(),
	}
}
