// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

type (
	GetClubByIdRequest struct {
		Id string `json:"id"`
	}
	GetClubByIdResponse struct {
		Result string `json:"result"`
	}
)
