// Code generated by microgen 1.0.4. DO NOT EDIT.

package transportgrpc

import (
	grpckit "github.com/go-kit/kit/transport/grpc"
	pb "github.com/justyntemme/wp/club/proto"
	transport "github.com/justyntemme/wp/club/transport"
	grpc "google.golang.org/grpc"
)

func NewGRPCClient(conn *grpc.ClientConn, addr string, opts ...grpckit.ClientOption) transport.EndpointsSet {
	return transport.EndpointsSet{GetClubByIdEndpoint: grpckit.NewClient(
		conn, addr, "GetClubById",
		_Encode_GetClubById_Request,
		_Decode_GetClubById_Response,
		pb.GetClubByIdResponse{},
		opts...,
	).Endpoint()}
}
