// Code generated by microgen 1.0.4. DO NOT EDIT.

// Please, do not change functions names!
package transportgrpc

import (
	"context"
	"errors"
	pb "github.com/justyntemme/wp/club/proto"
	transport "github.com/justyntemme/wp/club/transport"
)

func _Encode_GetClubById_Request(ctx context.Context, request interface{}) (interface{}, error) {
	if request == nil {
		return nil, errors.New("nil GetClubByIdRequest")
	}
	req := request.(*transport.GetClubByIdRequest)
	return &pb.GetClubByIdRequest{Id: req.Id}, nil
}

func _Encode_GetAllClubsNearMe_Request(ctx context.Context, request interface{}) (interface{}, error) {
	if request == nil {
		return nil, errors.New("nil GetAllClubsNearMeRequest")
	}
	req := request.(*transport.GetAllClubsNearMeRequest)
	return &pb.GetAllClubsNearMeRequest{Limit: req.Limit}, nil
}

func _Encode_GetClubById_Response(ctx context.Context, response interface{}) (interface{}, error) {
	if response == nil {
		return nil, errors.New("nil GetClubByIdResponse")
	}
	resp := response.(*transport.GetClubByIdResponse)
	return &pb.GetClubByIdResponse{Result: resp.Result}, nil
}

func _Encode_GetAllClubsNearMe_Response(ctx context.Context, response interface{}) (interface{}, error) {
	if response == nil {
		return nil, errors.New("nil GetAllClubsNearMeResponse")
	}
	resp := response.(*transport.GetAllClubsNearMeResponse)
	return &pb.GetAllClubsNearMeResponse{Result: resp.Result}, nil
}

func _Decode_GetClubById_Request(ctx context.Context, request interface{}) (interface{}, error) {
	if request == nil {
		return nil, errors.New("nil GetClubByIdRequest")
	}
	req := request.(*pb.GetClubByIdRequest)
	return &transport.GetClubByIdRequest{Id: string(req.Id)}, nil
}

func _Decode_GetAllClubsNearMe_Request(ctx context.Context, request interface{}) (interface{}, error) {
	if request == nil {
		return nil, errors.New("nil GetAllClubsNearMeRequest")
	}
	req := request.(*pb.GetAllClubsNearMeRequest)
	return &transport.GetAllClubsNearMeRequest{Limit: int32(req.Limit)}, nil
}

func _Decode_GetClubById_Response(ctx context.Context, response interface{}) (interface{}, error) {
	if response == nil {
		return nil, errors.New("nil GetClubByIdResponse")
	}
	resp := response.(*pb.GetClubByIdResponse)
	return &transport.GetClubByIdResponse{Result: string(resp.Result)}, nil
}

func _Decode_GetAllClubsNearMe_Response(ctx context.Context, response interface{}) (interface{}, error) {
	if response == nil {
		return nil, errors.New("nil GetAllClubsNearMeResponse")
	}
	resp := response.(*pb.GetAllClubsNearMeResponse)
	return &transport.GetAllClubsNearMeResponse{Result: string(resp.Result)}, nil
}
