// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: service.proto

package protobuf

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...client.CallOption) (*GetUserByIdResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...client.CallOption) (*GetUserByIdResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserById", in)
	out := new(GetUserByIdResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	GetUserById(context.Context, *GetUserByIdRequest, *GetUserByIdResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		GetUserById(ctx context.Context, in *GetUserByIdRequest, out *GetUserByIdResponse) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) GetUserById(ctx context.Context, in *GetUserByIdRequest, out *GetUserByIdResponse) error {
	return h.UserServiceHandler.GetUserById(ctx, in, out)
}
