// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

type (
	GetUserByIdRequest struct {
		Id string `json:"id"`
	}
	GetUserByIdResponse struct {
		Result string `json:"result"`
	}
)
