// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

import (
	"context"
	endpoint "github.com/go-kit/kit/endpoint"
	user "github.com/justyntemme/wp/user"
)

func Endpoints(svc user.UserService) EndpointsSet {
	return EndpointsSet{GetUserByIdEndpoint: GetUserByIdEndpoint(svc)}
}

func GetUserByIdEndpoint(svc user.UserService) endpoint.Endpoint {
	return func(arg0 context.Context, request interface{}) (interface{}, error) {
		req := request.(*GetUserByIdRequest)
		res0, res1 := svc.GetUserById(arg0, req.Id)
		return &GetUserByIdResponse{Result: res0}, res1
	}
}
