// Code generated by microgen 1.0.4. DO NOT EDIT.

package service

import service "github.com/justyntemme/wp/user"

// Service middleware (closure).
type Middleware func(service.UserService) service.UserService
