// Code generated by microgen 1.0.4. DO NOT EDIT.

package service

import (
	"context"
	"fmt"
	log "github.com/go-kit/kit/log"
	service "github.com/justyntemme/wp/user"
)

// RecoveringMiddleware recovers panics from method calls, writes to provided logger and returns the error of panic as method error.
func RecoveringMiddleware(logger log.Logger) Middleware {
	return func(next service.UserService) service.UserService {
		return &recoveringMiddleware{
			logger: logger,
			next:   next,
		}
	}
}

type recoveringMiddleware struct {
	logger log.Logger
	next   service.UserService
}

func (M recoveringMiddleware) GetUserById(ctx context.Context, s string) (rs string, err error) {
	defer func() {
		if r := recover(); r != nil {
			M.logger.Log("method", "GetUserById", "message", r)
			err = fmt.Errorf("%v", r)
		}
	}()
	return M.next.GetUserById(ctx, s)
}
