// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

type (
	GetVoteByIdRequest struct {
		VoteId string `json:"vote_id"`
	}
	GetVoteByIdResponse struct {
		Result string `json:"result"`
	}

	GetVotesByUserIdRequest struct {
		UserId string `json:"user_id"`
	}
	GetVotesByUserIdResponse struct {
		Result string `json:"result"`
	}

	GetVotesByClubIdRequest struct {
		ClubId string `json:"club_id"`
	}
	GetVotesByClubIdResponse struct {
		Result string `json:"result"`
	}
)
