// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

type (
	GetVoteByIdRequest struct {
		Id string `json:"id"`
	}
	GetVoteByIdResponse struct {
		Result string `json:"result"`
	}
)
