// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

import (
	"context"
	endpoint "github.com/go-kit/kit/endpoint"
	vote "github.com/justyntemme/wp/vote"
)

func Endpoints(svc vote.VoteService) EndpointsSet {
	return EndpointsSet{GetVoteByIdEndpoint: GetVoteByIdEndpoint(svc)}
}

func GetVoteByIdEndpoint(svc vote.VoteService) endpoint.Endpoint {
	return func(arg0 context.Context, request interface{}) (interface{}, error) {
		req := request.(*GetVoteByIdRequest)
		res0, res1 := svc.GetVoteById(arg0, req.Id)
		return &GetVoteByIdResponse{Result: res0}, res1
	}
}
