// Code generated by microgen 1.0.4. DO NOT EDIT.

package service

import service "github.com/justyntemme/wp/vote"

// Service middleware (closure).
type Middleware func(service.VoteService) service.VoteService
