name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        service: [user, club, vote]
    steps:
    - name: Copy directory to LXC Container
      run: |
        IMAGE_TAG=$(date +%s)
        lxc exec microk8s -- mkdir /tmp/$IMAGE_TAG
        lxc file push ./ microk8s/tmp/$IMAGE_TAG --recursive
    #   run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: |
        lxc exec microk8s -- docker build --cache-from localhost:32000/justyntemme/${{ matrix.service }}-svc . --file /tmp/$IMAGE_TAG/Dockerfile --target ${{ matrix.service }}-server-run --tag "localhost:32000/justyntemme/${{ matrix.service }}-svc:${{ github.sha }}"
    - name: Push the image
      run: |
        lxc exec microk8s -- docker push "localhost:32000/justyntemme/${{ matrix.service }}-svc:${{ github.sha }}"

     

   
