name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        service: [user, club, vote]
    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v2
    - name: copy-files
      if: steps.checkout-code.outcome == 'success'
      run: |
        IMAGE_TAG=$(date +%s)
        lxc exec microk8s -- mkdir /tmp/${{ github.sha }} || true
        lxc file push ./ microk8s/tmp/${{ github.sha }}/ --recursive
        
    #   run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: build-docker-image
      id: build-docker-image
      if: steps.copy-files.outcome == 'success'
      run: |
        IMAGE_TAG=$(date +%s)
        lxc exec microk8s -- /bin/bash -c "cd /tmp/${{ github.sha }}/wp/ && docker build --cache-from localhost:32000/justyntemme/${{ matrix.service }}-svc . --target ${{ matrix.service }}-server-run --tag "localhost:32000/justyntemme/${{ matrix.service }}-svc:${{ github.sha }}""

    - name: Push the image
      if: steps.build-docker-image.outcome == 'success'
      run: |
        lxc exec microk8s -- docker push "localhost:32000/justyntemme/${{ matrix.service }}-svc:${{ github.sha }}"
     

   
