name: Docker Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for user-server-run
      run: docker build . --file Dockerfile --target user-server-run --tag user-server:$(date +%s)

name: Go Test
on:
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.x
    - name: Run go test
      working-directory: ./${{ matrix.service }}
      run: |
        go test -v ./...