name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user, club, vote]
    steps:
    - uses: actions/checkout@v3
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: "docker.io/justyntemme/${{ matrix.service }}-svc"
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: |
        IMAGE_TAG=$(date +%s)
        echo "::set-output name=image_tag::$IMAGE_TAG"
        docker build --cache-from docker.io/justyntemme/${{ matrix.service }}-svc . --file Dockerfile --target ${{ matrix.service }}-server-run --tag "docker.io/justyntemme/${{ matrix.service }}-svc:${{ github.sha }}"
    - name: Push the image
      run: |
        docker push "docker.io/justyntemme/${{ matrix.service }}-svc:${{ github.sha }}"

     

   
