name: Deploy to microk8s

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install and configure microk8s
      run: |
        microk8s.config > ~/.kube/config
    
    - name: Install Helm
      run: |
        VERSION=$(curl --silent https://api.github.com/repos/helm/helm/releases/latest | grep tag_name | cut -d '"' -f 4)
        curl https://get.helm.sh/helm-$VERSION-linux-amd64.tar.gz -o helm.tar.gz
        tar -zxvf helm.tar.gz
        sudo mv linux-amd64/helm /usr/local/bin/
    
    - name: Deploy the Helm chart
      run: |
        helm init --client-only
        helm upgrade --install my-release my-chart --set image.tag=${{ github.sha }}
