name: Deploy to microk8s

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        service: [vote, club, user]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy the Helm chart
      run: |
        microk8s helm upgrade --install ${{ matrix.service }}-svc ./${{ matrix.service }}/deploy/${{ matrix.service }}-svc --set image.tag=${{ github.sha }}
