name: Go Test

on:
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.x
    - name: Run go test
      working-directory: ./${{ matrix.service }}
      run: |
      go test -v ./...
