name: Go Test

on: [pull-request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user, dal]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: latest
    - name: Run go test
      run: |
        go test -v ./${{ matrix.service }}/...
